---
#
# Boostrap Java - Tasks
#

- name: Check if bootstrap is needed
  raw: /bin/test -x {{jdk_home}}/bin/java
  register: need_boostrap
  ignore_errors: True

- name: Fetch java archive from control host
  raw: |
    /bin/wget -q -O /tmp/{{jdk_archive}} http://172.17.8.100/vagrant/provisioners/ansible/roles/java/files/{{jdk_archive}}
  when: need_boostrap | failed

- name: Extracting jdk
  raw: |
    mkdir -p {{pkg_home}}
    tar zx -C {{pkg_home}} -f /tmp/{{jdk_archive}}
  when: need_boostrap | failed

- name: Create link for java
  raw: |
    for file in `/bin/find {{jdk_home}}/bin -maxdepth 1 ! -name '*.ini' ! -name '*.cgi' -executable -type f`; do
      /bin/ln -s ${file} {{bin_home}}/${file##*/}
    done
  when: need_boostrap | failed